[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ROS Documentation"
authors = [{name = "Jeremy Wang", email = "jerewang@seas.upenn.edu"}]
dynamic = ["version", "description"]
